### ISSUE TITLE
Support for CircuitPython 8.1+

### ISSUE THREAD

**Issue by StoaferP** [aivarannamaa/pipkin#8]
Pipkin can't find mpy-cross for CircuitPython versions 8.1 or greater!  As you might imagine, I plan to follow up this issue with a PR addressing the issue.

P.S. This project is _essential_ for solid, clean CircuitPython workflows; thanks so much for all the work you've done!

**Comment by aivarannamaa** [comment]
Thanks! I had forgotten this file. Will update it for 9.0 already.
